    import express from 'express';
    import { generateToken } from '../middleware/csrf.js';

    const csrfRoutes = express.Router();

    /*
        CSRF token route
        the frontend calls this endpoint to get a CSRF token before making any POST, PUT, or DELETE requests
        the token is generated by csrf-sync and tied to the user's session
        the frontend then sends this token back in the request headers on every non-GET request
        if the token is missing or invalid, csrf-sync will reject the request with a 403
    */

    csrfRoutes.get('/csrf', (req, res) => {
        // generate a CSRF token for the current session and send it to the frontend
        const token = generateToken(req);
        res.json({ csrfToken: token });
    });

    export default csrfRoutes;